"""empty message

Revision ID: 4629b97c0977
Revises: 
Create Date: 2023-09-13 20:52:00.319534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4629b97c0977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('db_event_name', sa.String(length=80), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('user_ip_address', sa.String(length=15), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='role'), nullable=False),
    sa.Column('profile_picture', sa.String(length=20), nullable=False),
    sa.Column('account_status', sa.Enum('PENDING', 'DISABLED', 'CONFIRMED', name='accountstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(), nullable=False),
    sa.Column('industry_type', sa.String(length=100), nullable=False),
    sa.Column('reliability', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('actions_taken', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('year <= 2023', name='year_max_constraint'),
    sa.CheckConstraint('year >= 1900', name='year_min_constraint'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident')
    op.drop_table('user')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
